# Generated by Django 3.0.3 on 2020-03-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='courses/chapters/thumbnails/'),
        ),
    ]
